version: "3.8"

services:
  db:
    image: mysql:8
    container_name: laravel_db
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laravel
        MYSQL_USER: laravel_user
        MYSQL_PASSWORD: laravel_pass
    ports:
        - "3306:3306"
    volumes:
        - dbdata:/var/lib/mysql
    networks:
        - laravel

    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 5s
        timeout: 5s
        retries: 5

  app:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www
    user: "1000:1000"
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ../..:/var/www
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - ../..:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
